### ISSUE TITLE
Don't close

### ISSUE THREAD

**Issue by SillierShark195** [Aericio/PCEBookShop#11]
$warpmenu->getInventory();
					$inventory->setItem(0,Item::get(340, 1, 1)->setCustomName("§r§bCommon Enchantment Book")->setLore(["§r§cCost: 1000 XP"]));;
					$inventory->setItem(1,Item::get(340, 2, 1)->setCustomName("§r§eUncommon Enchantment Book")->setLore(["§r§cCost: 2000 XP"]));;
					$inventory->setItem(2,Item::get(340, 3, 1)->setCustomName("§r§6Rare Enchantment Book")->setLore(["§r§cCost: 3000 XP"]));;
					$inventory->setItem(3,Item::get(340, 4, 1)->setCustomName("§r§cMythic Enchantment Book")->setLore(["§r§cCost: 4000 XP"]));;
					$inventory->setItem(4,Item::get(340, 5, 1)->setCustomName("§r§3Special Enchantment Book")->setLore(["§r§cCost: 5000 XP"]));;
                    $warpmenu->send($sender);

                break;
        }

        return true;
    }
    
    public function handleWarpMenu(Player $player, Item $itemClicked, Item $itemClickedWith, SlotChangeAction $action): bool{
        //COMMON
        $cost = 1000;
       
       if($itemClicked->getId() === Item::BOOK and $itemClicked->getDamage() === 1) {
           $level = $player->getLevel();
                           $player->getLevel()->addSound(new AnvilBreakSound($player));
        if ($player->getCurrentTotalXp() < $cost ) {
            
			    $player->sendMessage(TextFormat::RED . "You do not have enough EXP to buy Common Book");

**Comment by Aericio** [comment]
Stop creating new issues. What does this even have to do with this plugin?
