### ISSUE TITLE
kicks on command run

### ISSUE THREAD

**Issue by IcyEndymion004** [Aericio/PCEBookShop#15]
05.04 06:37:44 [Server] CRITICAL Error: "Undefined class constant 'RARITY_NAMES'" (EXCEPTION) in "plugins/FUCKINGCESHOPBOOKSHITCRACKAIDS/src/Aericio/PCEBookShop/commands/BookShopCommand" at line 71
05.04 06:37:44 [Server] CRITICAL #0 plugins/FUCKINGCESHOPBOOKSHITCRACKAIDS/src/Aericio/PCEBookShop/commands/BookShopCommand(28): Aericio\PCEBookShop\commands\BookShopCommand->sendShopForm(object koth\KothPlayer)
05.04 06:37:44 [Server] CRITICAL #1 plugins/FUCKINGCESHOPBOOKSHITCRACKAIDS/src/Aericio/PCEBookShop/libs/CortexPE/Commando/BaseCommand(124): Aericio\PCEBookShop\commands\BookShopCommand->onRun(object koth\KothPlayer, string[2] bs, array[0])
05.04 06:37:44 [Server] CRITICAL #2 pmsrc/src/pocketmine/command/SimpleCommandMap(248): Aericio\PCEBookShop\libs\CortexPE\Commando\BaseCommand->execute(object koth\KothPlayer, string[2] bs, array[0])

**Comment by Aericio** [comment]
Appears to be a modified version of the plugin.
