### ISSUE TITLE
Plugin is not wokring

### ISSUE THREAD

**Issue by IcyEndymion004** [Aericio/PCEBookShop#16]
05.04 07:51:19 [Server] CRITICAL Error: "Class 'DaPigGuy\libPiggyEconomy\libPiggyEconomy' not found" (EXCEPTION) in "plugins/PCEBookShop-master/src/Aericio/PCEBookShop/PCEBookShop" at line 44
05.04 07:51:19 [Server] CRITICAL #0 pmsrc/src/pocketmine/plugin/PluginBase(116): Aericio\PCEBookShop\PCEBookShop->onEnable()
05.04 07:51:19 [Server] CRITICAL #1 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
05.04 07:51:19 [Server] CRITICAL #2 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object Aericio\PCEBookShop\PCEBookShop)
05.04 07:51:19 [Server] CRITICAL #3 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object Aericio\PCEBookShop\PCEBookShop)
05.04 07:51:19 [Server] CRITICAL #4 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
05.04 07:51:19 [Server] CRITICAL #5 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
05.04 07:51:19 [Server] CRITICAL #6 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
05.04 07:51:19 [Server] CRITICAL #7 pmsrc(11): require(string[103] phar:///PocketMine-MP.phar/src/po)
05.04 07:51:19 [Server] INFO Disabling PCEBookShop v1.0.3

**Comment by Aericio** [comment]
Not downloaded from poggit.
