### ISSUE TITLE
give book command - suggestion

### ISSUE THREAD

**Issue by jaylac2000** [Aericio/PCEBookShop#9]
Add a Admin/OP command /givebook >>ce<< >>level<< to give your self books, This would also be good to give books as an item inside of server crates (using the command)

**Comment by Aericio** [comment]
This is not within the scope of this plugin. Books are part of PiggyCustomEnchants.

**Comment by jaylac2000** [comment]
Ok, shall I make this suggestion on the main PiggyCustomEnchants plugin than?

**Comment by Aericio** [comment]
yes

**Comment by jaylac2000** [comment]
Alright
